tank-site/config/routes.rb
Rails.application.routes.draw do
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :index
  root 'index#index'
end

tank-site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tank-site/app/models/product.rb
class Product < ApplicationRecord
end

tank-site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tank-site/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

tank-site/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end



  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :image_url)
    end
end

tank-site/app/helpers/application_helper.rb
module ApplicationHelper
end

tank-site/app/helpers/index_helper.rb
module IndexHelper
end

tank-site/app/helpers/products_helper.rb
module ProductsHelper
  def print_price(price)
    number_to_currency(price, unit: '€')
  end

  def price=(input)
    self.price = input
  end
end

tank-site/app/views/index/index.html.erb
Hello

tank-site/app/views/layouts/_footer.html.erb
<footer>foot</footer>

tank-site/app/views/layouts/_header.html.erb
<header class="w-100">
  <div class="d-flex wrapper">
    <%= image_tag 'logo-1.png', :class => 'logo-header mx-auto' %>
  </div>
<!--  <nav class="nav-box mx-auto">
    <ul class="list-unstyled list-group">
      <li><a href=""></a></li>
      <li><a href=""></a></li>
      <li><a href=""></a></li>
    </ul>
  </nav>-->


</header>

tank-site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TankSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>

tank-site/app/views/products/_form.html.erb
<%= form_with model: product, local: true, :class => 'w-100' do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tank-site/app/views/products/_product.html.erb
<div class="card col col-md-5 border border-warning p-0 m-2">
  <div class="card-body">
    <div class="card-image"><%= image_tag product.image_url %></div>
    <div class="card-title"><%= link_to product.title, product_path(product.id) %></div>
    <div class="card-subtitle"><%= print_price(product.price) %></div>
    <p class="card-text"><%= product.description %></p>

  </div>
</div>

tank-site/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

tank-site/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="pt-5">Onze mixen</h1>

<div class="grid-container">
  <div class="row d-flex justify-content-around">
    <%= render @products %>
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

tank-site/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

tank-site/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= link_to 'Delete', product_path(@product), data: {confirm: "Really delete the product?"}, method: "delete" %>